/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Signal = IDL.Record({
  'rsi' : IDL.Float64,
  'tp1' : IDL.Float64,
  'tp2' : IDL.Float64,
  'ema9' : IDL.Float64,
  'macd' : IDL.Float64,
  'ema21' : IDL.Float64,
  'ema50' : IDL.Float64,
  'entry' : IDL.Float64,
  'volumeRatio' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'hasSignal' : IDL.Bool,
});
export const CoinSignalData = IDL.Record({
  'id' : IDL.Text,
  'signal' : Signal,
});
export const BacktestResult = IDL.Record({
  'profitableSignals' : IDL.Nat,
  'averageReturn' : IDL.Float64,
  'winRate' : IDL.Float64,
  'totalSignals' : IDL.Nat,
});
export const OHLCV = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const CryptoCoin = IDL.Record({
  'id' : IDL.Text,
  'currentPrice' : IDL.Float64,
  'name' : IDL.Text,
  'priceChange24h' : IDL.Float64,
  'marketCapRank' : IDL.Nat,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'getAllSignals' : IDL.Func([], [IDL.Vec(CoinSignalData)], []),
  'getBacktestResults' : IDL.Func([IDL.Text], [BacktestResult], ['query']),
  'getCoinOHLCV' : IDL.Func([IDL.Text], [IDL.Vec(OHLCV)], ['query']),
  'getCoinSignal' : IDL.Func([IDL.Text], [Signal], ['query']),
  'getTopCoins' : IDL.Func([], [IDL.Vec(CryptoCoin)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Signal = IDL.Record({
    'rsi' : IDL.Float64,
    'tp1' : IDL.Float64,
    'tp2' : IDL.Float64,
    'ema9' : IDL.Float64,
    'macd' : IDL.Float64,
    'ema21' : IDL.Float64,
    'ema50' : IDL.Float64,
    'entry' : IDL.Float64,
    'volumeRatio' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'hasSignal' : IDL.Bool,
  });
  const CoinSignalData = IDL.Record({ 'id' : IDL.Text, 'signal' : Signal });
  const BacktestResult = IDL.Record({
    'profitableSignals' : IDL.Nat,
    'averageReturn' : IDL.Float64,
    'winRate' : IDL.Float64,
    'totalSignals' : IDL.Nat,
  });
  const OHLCV = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const CryptoCoin = IDL.Record({
    'id' : IDL.Text,
    'currentPrice' : IDL.Float64,
    'name' : IDL.Text,
    'priceChange24h' : IDL.Float64,
    'marketCapRank' : IDL.Nat,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'getAllSignals' : IDL.Func([], [IDL.Vec(CoinSignalData)], []),
    'getBacktestResults' : IDL.Func([IDL.Text], [BacktestResult], ['query']),
    'getCoinOHLCV' : IDL.Func([IDL.Text], [IDL.Vec(OHLCV)], ['query']),
    'getCoinSignal' : IDL.Func([IDL.Text], [Signal], ['query']),
    'getTopCoins' : IDL.Func([], [IDL.Vec(CryptoCoin)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };