/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BacktestResult {
  'profitableSignals' : bigint,
  'averageReturn' : number,
  'winRate' : number,
  'totalSignals' : bigint,
}
export interface CoinSignalData { 'id' : string, 'signal' : Signal }
export interface CryptoCoin {
  'id' : string,
  'currentPrice' : number,
  'name' : string,
  'priceChange24h' : number,
  'marketCapRank' : bigint,
  'symbol' : string,
}
export interface OHLCV {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : bigint,
}
export interface Signal {
  'rsi' : number,
  'tp1' : number,
  'tp2' : number,
  'ema9' : number,
  'macd' : number,
  'ema21' : number,
  'ema50' : number,
  'entry' : number,
  'volumeRatio' : number,
  'stopLoss' : number,
  'hasSignal' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'getAllSignals' : ActorMethod<[], Array<CoinSignalData>>,
  'getBacktestResults' : ActorMethod<[string], BacktestResult>,
  'getCoinOHLCV' : ActorMethod<[string], Array<OHLCV>>,
  'getCoinSignal' : ActorMethod<[string], Signal>,
  'getTopCoins' : ActorMethod<[], Array<CryptoCoin>>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];